project/apps/accounts/urls.py
from django.urls import path 
from . import views

app_name='accounts' 
urlpatterns =[
               path('register/',views.RegisterUserView.as_view(),name="register"), 
               path('login/',views.LoginUserView.as_view(),name="login"),
               path('logout/',views.LogoutUserView.as_view(),name="logout"),
             ]

project/apps/articles/urls.py
from django.urls import path
from . import views

app_name="articles"
urlpatterns=[
    
    path('',views.show_articles,name="blog"),
    path('<slug:slug>/',views.show_blog_details,name='blog_details'),
    path('articlepdf/<int:article_id>',views.show_article_pdf,name="article_pdf")
]    

project/apps/mainapp/urls.py
from django.urls import path
import apps.mainapp.views as views

app_name="main"
urlpatterns=[
    path('',views.index,name='index'),
]

project/apps/places/urls.py
from django.urls import path
from . import views

app_name="places"
urlpatterns=[
    path('history/',views.show_garden_history,name="history"),
    path('parts/',views.show_garden_parts,name="parts"),
    path('part/<int:pk>',views.show_part_detail,name="part_detail"),
    path('pdf_path/',views.download_path_garden,name="pdf_path"),
    path('time_rules/',views.show_time_rules,name="time_rules"),
    path('contact/',views.contact_view,name="contact"),
]    

project/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.mainapp.urls',namespace='main'),name='main'),
    path('places/',include('apps.places.urls',namespace='places'),name='places'),
    path('blog/',include('apps.articles.urls',namespace='articles'),name='articles'),
    path('workshops/',include('apps.workshops.urls',namespace='workshops')),
    path('accounts/',include('apps.accounts.urls',namespace='accounts')),
    path('memories/',include('apps.memories.urls',namespace='memories')),
    path('search/',include('apps.search.urls',namespace='search')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

project/templates/partials/header.html
<div class="jumbotron">
<div class="row">
    <div class="col-md-8">
      <img src="{{media_url}}/images/logo/logo.png" class="rounded-circle img-100" alt="">
    </div>
    <div class="col-div-4">
      <form action="/search/" class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" name='q' type="search" placeholder="جستجو" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">جستجو</button>
      </form>
    </div> 
  </div>  
</div>

project/templates/partials/login_state.html
<ul class="navbar-nav ml-auto">
    {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href=""> کاربر گرامی <span><strong>{{user}}</strong></span> خوش آمدید <span class="sr-only">(current)</span></a>
            </li>
             <li class="nav-item active">
                <a class="nav-link" href=" {% url 'accounts:logout' %}"><strong>خروج</strong><span class="sr-only">(current)</span></a>
            </li>
        {% else %}
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:login' %}"><strong>ورود</strong><span class="sr-only">(current)</span></a> 
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:register' %}"><strong>ثبت نام</strong><span class="sr-only">(current)</span></a> 
        </li> 
    {% endif %}
</ul> 

project/templates/partials/messages.html
{% if messages %}
    {% for message in messages  %}
    {% comment %} bootstrap class 'success' 'danger' {% endcomment %}
    <h2 class="atert alert-{{message.tags}}">{{message}}</h2>  
    {% endfor %}
{% endif %}

project/templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url "main:index" %}">باغ فردوس</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse header" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url "main:index" %}">صفحه اصلی <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            معرفی باغ
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url "places:history" %}">تاریخچه</a>
            <a class="dropdown-item" href="{% url "places:parts" %}">بخشهای باغ</a>
            <a class="dropdown-item" href="{% url "places:pdf_path" %}">مسیریابی</a>
            <a class="dropdown-item" href="{% url "places:time_rules" %}">برنامه و قوانین</a>
            <div class="dropdown-divider"></div>
          </div>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#">گالری</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="{% url "memories:showmemories" %}">خاطرات بازدید</a>
          </li>
          
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'memories:registermemory' %}">درج خاطره</a> </li>
          {% endif %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               آموزش و پژوهش
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url "articles:blog" %}">مقالات</a>
              <a class="dropdown-item" href="{% url "workshops:workshop" %}">کارگاه ما</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="{% url "places:contact" %}">تماس با ما</a>
          </li>
      </ul>
       {% include "partials/login_state.html" %} 
    </div>
  </nav>

project/templates/partials/paginator.html
{% comment %}pagination{% endcomment %}
  <nav aial-label="page navigation example">
    <ul class="pagination justify-content-center">
      {% comment %}previous{% endcomment %}
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">قبلی</a>
        </li>
      {% else %}
        <li class="page-item" disabled>
          <a clas="page-link" href="#" tabindex="-1" aria-disabled="True">قبلی</a>
        </li>
      {% endif %}
      {% comment %}pager{% endcomment %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active" aria-current="page">
            <span class="page-link">
              {{ i }}
              <span class="sr-only">(current)</span>
            </span>
          </li>
        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% comment %}hellpi{% endcomment %}
      {% if page_obj.number|add:'-4' > 1 %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.number|add:'-5'}}">&hellpi;</a>
        </li>
      {% endif %}
      {% comment %}next{% endcomment %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">بعدی</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-list" href="#" tabindex="-1" aria-disabled="True">بعدی</a>
        </li>
      {% endif %}
    </ul>
  </nav>

project/templates/partials/script.html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> 
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    function like (id) {
        $.ajax({
        type: "GET",
        url:"{% url 'memories:like'%}",
        data: {
        memory_id: id,
    };
    success: function (res) {
        $('#icon_like'+id).removeClass('bi-heart');
        $('#icon_like'+id).addClass('bi-heart-fill');
    }
    }); 
    } 
</script> 

project/templates/partials/slider.html
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{{media_url}}/images/slider/2.jpg" alt="1th slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{{media_url}}/images/slider/1.jpg" alt="2th slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{{media_url}}/images/slider/3.jpg" alt="3th slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{{media_url}}/images/slider/4.jpg" alt="4th slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{{media_url}}/images/slider/5.jpg" alt="5th slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{{media_url}}/images/slider/6.jpg" alt="6th slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{{media_url}}/images/slider/7.jpg" alt="7th slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{{media_url}}/images/slider/8.jpg" alt="8th slide">
      </div> 
    </div>
    <a class="carousel-control-prev" href="" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>