project/apps/places/urls.py
from django.urls import path
from . import views

app_name="places"
urlpatterns=[
    path('history/',views.show_garden_history,name="history"),
    path('parts/',views.show_garden_parts,name="parts"),
    path('part/<int:pk>',views.show_part_detail,name="part_detail"),
    path('pdf_path/',views.download_path_garden,name="pdf_path"),
    path('time_rules/',views.show_time_rules,name="time_rules"),
    path('contact/',views.contact_view,name="contact"),
]    

project/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.mainapp.urls',namespace='main'),name='main'),
    path('places/',include('apps.places.urls',namespace='places'),name='places'),
    path('blog/',include('apps.articles.urls',namespace='articles'),name='articles'),
    path('workshops/',include('apps.workshops.urls',namespace='workshops')),
    path('accounts/',include('apps.accounts.urls',namespace='accounts')),
    path('memories/',include('apps.memories.urls',namespace='memories')),
    path('search/',include('apps.search.urls',namespace='search')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

project/apps/places/models.py
from django.db import models
from django.utils import timezone

class Place(models.Model):
    place_name=models.CharField(max_length=100,verbose_name='نام مکان')
    information=models.TextField(verbose_name='توضیحات',default='توضیحات')
    place_image_name=models.ImageField(upload_to='images/places/',verbose_name='تصویر')
    visiting_day=models.CharField(max_length=100,verbose_name='روزهای بازدید')
    visiting_hour=models.CharField(max_length=100,verbose_name='ساعت بازدید')
    rules=models.TextField(verbose_name='قوانین و مقررات')
    register_date=models.DateTimeField(default=timezone.now,verbose_name='تاریخ و زمان ثبت')
    
    def __str__(self):
        return self.place_name
    
    class Meta:
        verbose_name='مکان'
        verbose_name_plural='مکانها'
        db_table='t_Places'
        
class VisitorType(models.Model):
    type_name=models.CharField(max_length=100,verbose_name='نام نوع بازدید کننده')
    
    def __str__(self):
        return self.type_name
    
    class Meta:
        verbose_name='نوع بازدید کننده'
        verbose_name_plural='نوع بازدید کننده ها'
        db_table='t_visitor-type'

class TicketPrice(models.Model):
    place=models.ForeignKey(Place,on_delete=models.CASCADE,verbose_name='مکان مورد نظر')
    visitor_type=models.ForeignKey(VisitorType,on_delete=models.CASCADE,verbose_name='نوع بازدید کننده')
    price=models.IntegerField(default=0,verbose_name='بهای بلیط')
    
    def __str__(self):
        return f"{self.place}\t{self.visitor_type}\t{self.place}"
    
    class Meta:
        verbose_name='قیمت'
        verbose_name_plural='قیمت ها'
        db_table='t_ticket_prices'
        
class Message(models.Model):
    full_name=models.CharField(max_length=60,verbose_name='نام و نام خانوادگی')
    email=models.EmailField(max_length=250,verbose_name='ایمیل')
    subject=models.CharField(max_length=200,verbose_name=' عنوان پیام')
    message=models.TextField(verbose_name='متن پیام')
    is_seen=models.BooleanField(default=False,verbose_name='وضعیت مشاهده توسط مدیر')
    register_date=models.DateTimeField(default=timezone.now,verbose_name='تاریخ ثبت پیام')
    
    def __str__(self):
        return self.full_name+""+self.subject
    class Meta:
        verbose_name='پیام'
        verbose_name_plural='پیام ها'
        db_table='t_message'
    

project/apps/places/forms.py
from django import forms
class MessageForm(forms.Form):
    full_name=forms.CharField(label='نام و نام خانوادگی')
    email=forms.EmailField(label='ایمیل')
    subject=forms.CharField(label=' عنوان پیام')
    message=forms.CharField(label='متن پیام',widget=forms.Textarea)

project/apps/places/views.py
from django.shortcuts import render,redirect
from .models import Place,TicketPrice,Message
from django.http import Http404
from django.core.files.storage import FileSystemStorage
from  django.http import HttpResponse,HttpResponseNotFound
from .forms import MessageForm
from django.contrib import messages

def show_garden_history(request):
    return render(request,'places/history.html')

def show_garden_parts(request):
    places=Place.objects.all
    context={
        'places':places
    }
    return render(request,"places/parts.html",context)
    
def show_part_detail(request,pk):
    try: 
        place=Place.objects.get(id=pk)
    except Place.DoesNotExist:
        raise Http404('صفحه یافت نشد')    
    context={
        'place':place
    }
    return render(request,"places/part_detail.html",context)

def download_path_garden(request):
    fs=FileSystemStorage()
    file_name="pdf_files/ferdowsGardenPath.pdf"
    if fs.exists(file_name):
        with fs.open(file_name) as pdf:
            response=HttpResponse(pdf,content_type="application/pdf")
            response['Content_Disposition']="attachment;filename='ferdowsGardenPath.pdf"
        
            return response
    else:
        HttpResponseNotFound('File not found ...')       

def show_time_rules(request):
    places=Place.objects.all()
    ticket_price=TicketPrice.objects.all() 
    context={
        'places':places,
        'ticket_price':ticket_price,
    }    
    return render(request,'places/time_rules.html',context)

def contact_view(request):
    form=MessageForm(request.POST)
    if form.is_valid():
        cd=form.cleaned_data
        msg=Message()
        msg.full_name=cd['full_name']
        msg.email=cd['email']
        msg.subject=cd['subject']
        msg.message=cd['message']
        msg.save()
        messages.success(request,"پیام شما ارسال شد","success")
        return redirect("main:index")
    return render(request,'places/contact.html',{'form':form})

project/templates/places/contact.html
{% extends "maintemplate.html" %}

{% block title %}تماس با ما | باغ فردوس{% endblock title %}

{% block content %}
<div class="container">
    <div style="text-align:right">
      <h2>تماس با ما</h2>
    </div>
    <div class="row">
        <div class="column">
            <div class="form-box">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form.as_table}}<br>
                    <input type="submit" value="ارسال پیام">
                </form> 
            </div> 
        </div>   
        
    </div>
</div>
{% endblock content %}

project/templates/places/history.html
{% extends "maintemplate.html" %}

{% block title %}تاریخچه باغ فردوس{% endblock title %}

{% block content %}
    <img src="{{media_url}}/images/history/1.jpg" alt="ddd">
    <p>
        داستان باغ فردوس با عمارت‌های رنگین و شگفت‌انگیز در دل باغ‌هایی بزرگ، از آن‌هایی که تا چشم کار می‌کند باغ است و عمارت‌های باشکوه از زمان محمدشاه قاجار شروع شد!


همان زمانی که شاهان قاجار باغ‌های زیادی را در مناطق مختلف تهران و کرج می‌ساختند. باغ فردوس آن زمان شامل زمین‌های اسدآباد و ولنجک در شمال، الهیه در جنوب، تجریش از شرق و محمودیه از غرب بوده است!
این باغ از دوران قاجار تا کنون حسابی دست به دست چرخیده و هر زمان که دست یک مالک بوده، بخشی از آن تکمیل شده و البته در دست برخی از مالکان هم بی‌مهری‌هایی دیده است.


باغی که فضای مشجر و سرسبز آن دارای بخش‌ها و عمارت‌های مختلف بوده که مشهورترین آن‌ها همین عمارت موزه سینمای فعلی با معماری زیبا و شگفت‌انگیز است.


از تزئینات، گچ‌بری‌ها و آینه‌کاری‌های چشم‌نواز آن که بگذریم، نوع معماری باغ فردوس هم منحصر به فرد است که در ادامه بیشتر آن را بررسی خواهیم کرد.
    </p>
{% endblock content %}

project/templates/places/part_detail.html
{% extends "maintemplate.html" %}

{% block title %}جزئیات مکان{% endblock title %}

{% block content %}
    <h1>{{place.place_name}}</h1>
    <img src="{{media_url}}/{{place.place_image_name}}" alt="">
    <p>{{place.information}}</p>
{% endblock content %}

project/templates/places/parts.html
{% extends "maintemplate.html" %}

{% block title %}باغ فردوس{% endblock title %}

{% block content %}
    <h1 class="text-center text-secondary">بخشهای باغ</h1>
<div class="row">
    {% for place in places  %}
        {% comment %} {{place.place_name}}
        {{place.place_image_name}}
        {{place.information}}
         {% endcomment %}
        <div class="col-sm-6 col-md-4 col-lg-4">
            <div class="thumbnail">
                <img src="{{media_url}}/{{place.place_image_name}}" alt="" class="img-300X200">
            </div>
            <div class="caption">
                <h3>{{place.place_name}}</h3>
                <p class="description">{{place.information}}</p>
                <p>
                    <a href="{% url "places:part_detail" pk=place.id %}" class="btn btn-primary btn-block role="button>
                        مشاهده جزئیات
                    </a>
                </p>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}

project/templates/places/time_rules.html
{% extends "maintemplate.html" %}

{% block title %}زمانبندی بازدیدوقوانین باغ فردوس{% endblock title %}

{% block content %}
<h2>روز و زمان بازدید</h2>
<ul>
    {% for place in  places %}
        <li>
            <strong>{{place.place_name}}</strong> : <strong class="value1">{{place.visiting_day}}</strong> | <strong>{{place.visiting_hour}}</strong>
            <br>
        </li>
    {% endfor %} 
</ul>
<hr>
<h1>نرخ بلیط ها</h1>
<ul>
    {% for ticket in ticket_price  %}
        <li>
            
            <strong>{{ticket.place}}</strong>
            <span>برای بازدید کننده</span>
            <strong>{{ticket.visitor_type}}</strong>
            <span>:</span>
            <strong class="value1">{{ticket.price}}</strong>
        </li>
    {% endfor %}
</ul>
<hr>
<h1>قوانین و مقررات</h1>
    {% for place in places %}
        <strong >{{place.place_name}}</strong><br>
        {% autoescape off %}
            {{place.rules}}<br>
        {% endautoescape %}
    {% endfor %}
{% endblock content %}