project/apps/workshops/urls.py
from django.urls import path
from apps.workshops.views import *

app_name="workshops"
urlpatterns=[
    path('',ShowWorkshopList.as_view(),name="workshop"),
    path('workshopreport/<int:pk>',ShowWorkshopReport.as_view(),name="workshopreport"),
]    

project/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.mainapp.urls',namespace='main'),name='main'),
    path('places/',include('apps.places.urls',namespace='places'),name='places'),
    path('blog/',include('apps.articles.urls',namespace='articles'),name='articles'),
    path('workshops/',include('apps.workshops.urls',namespace='workshops')),
    path('accounts/',include('apps.accounts.urls',namespace='accounts')),
    path('memories/',include('apps.memories.urls',namespace='memories')),
    path('search/',include('apps.search.urls',namespace='search')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

project/apps/workshops/models.py
from django.utils import timezone
from django.db import models


class WorkshopStatus(models.Model):
    status_code=models.IntegerField(primary_key=True,verbose_name='کدوضعیت')
    status_title=models.CharField(max_length=50,verbose_name='عنوان وضعیت')
    
    def __str__(self):
        return self.status_title
    
    class Meta:
        verbose_name='وضعیت'
        verbose_name_plural='وضعیت ها'
        db_table='t_workshopstatus'
        
def upload_workshop_image(instance,filename):
    return f"images/workshops/{filename}"

class Workshop (models.Model):
    title=models.CharField(max_length=200, verbose_name='عنوان')
    image_name=models.ImageField(upload_to=upload_workshop_image,max_length=50,verbose_name='تصویراصلی')
    date_time=models.DateTimeField(verbose_name='تاریخ و زمان برگزاری')
    place=models.CharField(max_length=50, verbose_name='مکان برگزاری')
    teacher=models.CharField(max_length=50,verbose_name='مدرس')
    information=models.TextField(verbose_name='اطلاعات')
    registration=models.TextField(verbose_name='شرایط ثبت نام')
    report_text=models.TextField(verbose_name='متن گزارش', null=True, blank=True) 
    view_number = models.IntegerField(default=0, verbose_name='تعدادبازدید')
    register_date=models.DateTimeField(default=timezone.now, verbose_name='تاریخ ثبت')
    is_active=models.BooleanField(default=False, verbose_name='وضعیت')
    status=models.ForeignKey(WorkshopStatus, on_delete=models. CASCADE, verbose_name='وضعیت کارگاه')
    
    def __str__(self):
        return f"{self.title}"
    
    class Meta:
        verbose_name = 'کارگاه'
        verbose_name_plural='کارگاه ها'
        db_table='t_workshop'
        
def upload_gallery_image(instance,filename):
    return f"images/workshops/report/{instance.workshop.id}/{filename}"
    
class WorkshopGallery(models.Model):
    workshop=models.ForeignKey(Workshop,on_delete=models.CASCADE,verbose_name='کارگاه') 
    image=models.ImageField(upload_to=upload_gallery_image,verbose_name='تصویر')
   
    def __str__(self):
        return f"{self.workshop}"
    
    class Meta:
        verbose_name = 'تصویر'
        verbose_name_plural='تصاویر'
        db_table='t_workshogallery'
    

project/apps/workshops/views.py
import os
from django.conf import settings
from django.http import Http404
from django.shortcuts import render
from django.views.generic.list import ListView 
from django.views.generic.detail import DetailView 
from .models import *

class ShowWorkshopList(ListView):
    model=Workshop
    template_name='workshops/workshoplist.html'
    context_object_name='workshops'
    queryset=Workshop.objects.order_by('-is_active') 
    paginate_by=3
    
class ShowWorkshopReport(DetailView):
    model=Workshop
    template_name='workshops/workshopdetail.html'
    context_object_name='workshops'
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs) 
        pk=self.kwargs['pk']
        try:
            workshop=Workshop.objects.get(id=pk) 
            workshop.view_number+= 1 
            workshop.save()
            path=settings.MEDIA_ROOT+'/images/workshops/report/'+str(pk) 
            if os.path.isdir(path):
                image_list=os.listdir(path)
                context['image_list']=image_list
            return context
        except Workshop.DoesNotExist:
            raise Http404("Workshop not found.")
        

project/templates/workshops/workshopdetail.html
{% extends 'maintemplate.html' %}
{% block title %}گزارش کارگاه{% endblock %}
{% block content %}
<main>
<section class="workshopreport-viewnumber">
<span>تعداد بازدید گزارش :<strong class="badg-success"> {{workshops.view_number}} </strong> بازدید</span>
</section>
<hr>
<section class = "workshopreport-section2">
<h3> متن گزارش کارگاه </h3>
{% autoescape off %}
{{workshops.report_text}}
{% endautoescape %}
</section>
<section class = "workshopreport-section3">
{% if image_list%}
    {% for image in image_list %}
    <img src="{{media_url}}images/workshops/report/{{workshops.id}}/{{image}}" class="img-300x200" alt="{{workshop.title}}"> 
    {% endfor %}
{% endif %}
</section>
</main>
{% endblock %}

project/templates/workshops/workshoplist.html
{% extends 'maintemplate.html' %}
{% block title %}
  گارگاه ها
{% endblock %}
{% block content %}
  <main>
    <section class="workshoplist-section1">
      {% for workshop in workshops %}
        <section class="workshoplist-section1__1">
          <i class="glyphicon glyphicon-bullhorn"></i>
          <h2>{{ workshop.title }}</h2>
        </section>
        <section class="workshoplist-section1__2">
          <img src="{{ media_url }}{{ workshop.image_name }}" alt="{{ workshop.title }}" class="img-300x200" />
        </section>
        <section class="workshoplist-section1__3">
          <strong>تاریخ و زمان برکزاری : </strong>{{ workshop.date_time }}<br>
          <strong>مکان بر گزاری : </strong>{{ workshop.place }}<br>
          <strong>مدرس : </strong>{{ workshop.teacher }}<br>
          <strong>اطلاعات : </strong>{{ workshop.information }}<br>
          <strong>شرایط ثبت نام : </strong>{{ workshop.registration }}<br>
        </section>
        <section class="workshoplist-section1__4">
          {% if workshop.status_id == 3 %} 
            <a class="btn btn-success" href="{% url 'workshops:workshopreport' workshop.id %}">مشاهده گزارش کارگاه</a>
          {% endif %}    
        </section>
        <hr>
      {% endfor %} 
    </section>
  </main>
  
{% include "partials/paginator.html" %} 
{% endblock %}