project/apps/articles/urls.py
from django.urls import path
from . import views

app_name="articles"
urlpatterns=[
    
    path('',views.show_articles,name="blog"),
    path('<slug:slug>/',views.show_blog_details,name='blog_details'),
    path('articlepdf/<int:article_id>',views.show_article_pdf,name="article_pdf")
]    

project/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.mainapp.urls',namespace='main'),name='main'),
    path('places/',include('apps.places.urls',namespace='places'),name='places'),
    path('blog/',include('apps.articles.urls',namespace='articles'),name='articles'),
    path('workshops/',include('apps.workshops.urls',namespace='workshops')),
    path('accounts/',include('apps.accounts.urls',namespace='accounts')),
    path('memories/',include('apps.memories.urls',namespace='memories')),
    path('search/',include('apps.search.urls',namespace='search')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

project/apps/articles/models.py
from django.db import models

class Author(models.Model):
    name=models.CharField(max_length=20,verbose_name='نام')
    family=models.CharField(max_length=20,verbose_name='فامیلی')
    email=models.EmailField(max_length=200,verbose_name='ایمیل',null=True,blank=True)
    mobile=models.CharField(max_length=11,verbose_name='موبایل',null=True,blank=True )
    is_active=models.BooleanField(default=False,verbose_name='وضعیت')
    slug=models.SlugField(max_length=200)
    
    def __str__(self):
        return self.name+""+self.family
    
    class Meta:
        verbose_name='نویسنده'
        verbose_name_plural='نویسندگان'
        db_table='t_authors'
        
class ArticleGroup(models.Model):
    group_title=models.CharField(max_length=100,verbose_name='عنوان گروه مقالات')
    
    def __str__(self):
        return self.group_title
    
    class Meta:
        verbose_name='گروه مقاله'
        verbose_name_plural='گروه مقالات'
        db_table='t_article_groups'
        
from django.utils import timezone
class Article(models.Model):
    group=models.ForeignKey(ArticleGroup,on_delete=models.CASCADE,verbose_name='گروه مقاله')
    author=models.ManyToManyField(Author,verbose_name='نویسنده مقاله') 
    title=models.CharField(max_length=200,verbose_name='عنوان مقاله') 
    image_name=models.CharField(max_length=100,verbose_name='تصویراصلی مقاله')
    short_text=models.TextField(verbose_name='متن خلاصه مقاله')
    text=models.TextField(verbose_name='متن مقاله')
    key_words=models.CharField(max_length=200,verbose_name='کلمات کلیدی مقاله')
    register_date=models.DateField(auto_now_add=True,verbose_name='تاریخ درج مقاله')
    publish_date=models.DateField(default=timezone.now,verbose_name='تاریخ انتشار مقاله')
    update_date=models.DateField(auto_now=True,verbose_name='تاریخ آخرین ویرایش مقاله ')
    is_active=models.BooleanField(default=False,verbose_name='وضعیت')
    pdf_file_name=models.CharField(max_length=200,verbose_name='فایل pdfمقاله')
    view_number=models.PositiveSmallIntegerField(default=0,verbose_name='تعداد بازدید')   
    slug=models.SlugField(max_length=200)
    
    def __str__(self):
        return self.title
  
    class Meta:
        verbose_name='مقاله'
        verbose_name_plural='مقالات'
        db_table='t_articles'
        
class ArticleGallery(models.Model):
    image_name=models.CharField(max_length=100,verbose_name='نام تصویر')
    article=models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name='مقاله')
    
    def __str__(self):
        return self.image_name
  
    class Meta:
        verbose_name='تصویر'
        verbose_name_plural='تصاویر'
        db_table='t_article_gallery'

project/apps/articles/views.py
import os
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render,redirect
from django.db import models
from .models import *
from django.conf import settings
from django.core.files.storage import FileSystemStorage

def show_articles(request):
    articles=Article.objects.filter(is_active=True)
    articles_authors=Article.author.through.objects.all()
    authors=Author.objects.all()
    context={ 
        'articles':articles,
        'authors':authors,
        'articles_authors':articles_authors,
    }
    return render(request,'articles/blog.html',context)
    
def show_blog_details(request,slug):
    article=Article.objects.get(slug=slug)
    articles_authors=Article.objects.get(id=article.id).author.through.objects.all()
    authors=Author.objects.all()
    image_list=os.listdir(settings.MEDIA_ROOT+'/images/articles/article_'+str(article.id))
    article.view_number+=1
    article.save()
    context={
        'article':article,
        'articles_authors':articles_authors,
        'authors':authors,
        'image_list':image_list,
    }
    return render(request,'articles/blog_details.html',context)

def show_article_pdf (request,article_id): 
    fs=FileSystemStorage()
    filename='article_'+str(article_id)+'.pdf'
    file_path="pdf_files/"+filename
    if fs.exists(file_path):
        with fs.open(file_path) as pdf:
            response=HttpResponse(pdf,content_type ='application/pdf') 
            response['Content-Disposition']='inline;filename='+filename
        return response
    else: 
        return HttpResponseNotFound('The requested pdf file ws not found in our server')
    
    
    
    
  

project/templates/articles/blog.html
{% extends "maintemplate.html" %}

{% block title %}باغ فردوس{% endblock title %}

{% block content %}
    <h1 class="h1-center text-secondary">مقالات</h1>
    <hr>
<div class="row">
    {% for article in articles %}
        <div class="col-sm-6 col-md-4 col-lg-4">
            <div class="thumbnail">
                <img src="{{media_url}}images/articles/{{article.image_name}}" alt="{{article.title}}" class="img-300X200">
            </div>
            <div >
            <div class="caption">
                <h2 class="h3-center">{{article.title}}</h2><hr>
                <p class="description">{{article.short_text}}</p>
                <hr>
                <strong>نوع مقاله : </strong>{{article.group}}<strong> | تاریخ انتشار : </strong> {{article.update_date}}<strong> | تعداد بازدید : </strong>{{article.view_number}}
                <strong>نویسندگان :</strong>
                {% for i in articles_authors %}
                    {% if i.article_id == article.id %}
                        {% for author in authors  %}
                            {% if i.author_id == author.id %}
                                {{author.name}} {{author.family}}&nbsp;&nbsp;
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endfor %}
            </div>
                <p>
                    <a href="{% url "articles:blog_details" slug=article.slug %}" class="btn btn-primary btn-block role="button>
                        <strong>مشاهده مقاله</strong>
                    </a>
                </p>
            </div>
        </div>
    {% endfor %}
</div> 
{% endblock content %}

project/templates/articles/blog_details.html
{% extends "maintemplate.html" %}

{% block title %}مقاله{% endblock title %}

{% block content %}
<div>
        <div class="col-sm-6 col-md-4 col-lg-4">
            <div class="caption">
                <h2 class="h3-center">{{article.title}}</h2><hr>
                <strong>گروه مقاله :</strong> {{article.group}}<br>
                <strong>نویسندگان :</strong>
                {% for i in articles_authors %}
                    {% for author in authors  %}
                        {% if i.author_id == author.id %}
                            {{author.name}} {{author.family}}&nbsp;&nbsp;
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </div> 
            <strong>چکیده : </strong>{{article.short_text}}<br> 
            <strong>کلمات کلیدی :</strong> {{article.key_words}}<br>
            <strong>تعداد بازدید :</strong> {{article.view_number}}<br>
            <strong>متن مقاله :</strong> {{article.text}}<br>
        </div>
        <strong>تصاویر مرتبط با مقاله :</strong><br>
        {% for image in image_list  %}
        <a target="_blank" href="{{media_url}}/images/articles/article_{{article.id}}/{{image}}" alt="{{article.title}}">
            <img src="{{media_url}}/images/articles/article_{{article.id}}/{{image}}" alt="{{article.title}}">
        </a>
        {% endfor %}
        <br>
        <strong><a  href="{% url "articles:article_pdf" article.id %}">دانلود متن مقاله</a></strong>
</div> 
{% endblock %}